### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by eternaleclipse** [eternaleclipse/chess-mazes#5]
A button that enables Dark mode. This would involve adding a button to `GameView` and corresponding handler function in `ViewModel` that tracks the current status of dark mode, including saving it to LocalStorage, and adding some dark versions of CSS classes to have the design appear visually appealing in dark mode.

This is not a crucial, since anyone that really cares about Dark mode already has a browser extension, but:
1. It would be nice to support it natively.
2. Users playing from mobile don't have that option.

**Comment by zivattias** [comment]
I'll gladly do it.

**Comment by eternaleclipse** [comment]
#10
